services:
  wordpress:
    build: .
    container_name: industry_wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: industry_db
      WORDPRESS_DB_USER: industry_admin
      WORDPRESS_DB_PASSWORD: industry_password123
    volumes:
      - ./backups:/var/www/backups
      - ./html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wordpress_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: industry_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: industry_db
      MYSQL_USER: industry_admin
      MYSQL_PASSWORD: industry_password123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: industry_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
    driver: bridge
