<?php
vc_map( array(
			'base'		=> 'sc_separator',
			'name'			=> esc_html__( 'جداکننده', 'studiare' ),
			'description'	=> esc_html__( 'جدا کننده ردیف ها و صفحه ها', 'studiare' ),
			'category'         => esc_html__( 'اختصاصی قالب', 'studiare' ),
			'icon'			=> 'admin_vc_addon',
			'params'		=> array(
				array(
					"type"        	=> "dropdown",
					"heading"     	=> esc_html__('طرح جداکننده را انتخاب کنید', 'studiare'),
					"param_name"  	=> "style",
					'edit_field_class' => 'vc_col-xs-99 xtra-image-select-3',
					'value'			=> array(
						'1' 	=> '1',
						'2' 	=> '2',
						'3' 	=> '3',
						'4' 	=> '4',
						'5' 	=> '5 ',
						'6' 	=> '6 ',
						'7' 	=> '7 ',
						'8' 	=> '8 ',
						'9' 	=> '9 ',
						'11' 	=> '11',
						'12' 	=> '12',
						'13' 	=> '13',
						'14' 	=> '14',
						'15' 	=> '15',
						'16' 	=> '16',
						'17' 	=> '17',
						'18' 	=> '18',
						'19' 	=> '19',
						'20' 	=> '20',
						'21' 	=> '21',
						'22' 	=> '22',
						'23' 	=> '23',
						'24' 	=> '24',
						'25' 	=> '25',
						'26' 	=> '26',
						'27' 	=> '27',
						'28' 	=> '28',
						'29' 	=> '29',
						'30' 	=> '30',
						'31' 	=> '31',
						'32' 	=> '32',
						'33' 	=> '33',
						'34' 	=> '34',
						'35' 	=> '35',
						'36' 	=> '36',
						'37' 	=> '37',
						'38' 	=> '38',
						'39' 	=> '39',
						'40' 	=> '40',
						'41' 	=> '41',
						'42' 	=> '42',
						'43' 	=> '43',
						'44' 	=> '44',
						'45' 	=> '45',
						'46' 	=> '46',
						'47' 	=> '47',
						'48' 	=> '48',
						'49' 	=> '49',
						'50' 	=> '50',
						'51' 	=> '51',
						'52' 	=> '52',
						'53' 	=> '53',
						'54' 	=> '54',
						'55' 	=> '55',
						'56' 	=> '56',
						'57' 	=> '57',
						'58' 	=> '58',
						'59' 	=> '59',
						'60' 	=> '60',
						'61' 	=> '61',
						'62' 	=> '62',
						'63' 	=> '63',
						'64' 	=> '64',
						'65' 	=> '65',
						'66' 	=> '66',
						'67' 	=> '67',
					),
					'std'			=> '1',
					'admin_label' 	=> true
				),
				array(
					'type' 			=> 'dropdown',
					'heading' 		=> esc_html__('تغییر شکل', 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					'param_name' 	=> 'transform',
					'value'		=> array(
						'بالا' 						=> 'sc_sep_top',
						'بالا - چرخش افقی' 		=> 'sc_sep_rotatey_top',
						'پایین' 					=> 'sc_sep_bottom',
						'پایین - چرخش افقی' 	=> 'sc_sep_rotatey_bottom',
					),
					'std' 		 	=> 'cz_sep_bottom'
				),
				array(
					"type"        	=> "textfield",
					"heading"     	=> esc_html__( "عرض", 'studiare' ),
					"param_name"  	=> "sep_width",
					'options' 		=> array( 'unit' => '%', 'step' => 1, 'min' => 100, 'max' => 300 ),
					'edit_field_class' => 'vc_col-xs-99'
				),
				array(
					"type"        	=> "textfield",
					"heading"     	=> esc_html__( "ارتفاع", 'studiare' ),
					"param_name"  	=> "sep_height",
					'options' 		=> array( 'unit' => 'px', 'step' => 1, 'min' => 10, 'max' => 500 ),
					'edit_field_class' => 'vc_col-xs-99',
					'value' 		=> '200px'
				),
				array(
					"type"        	=> "textfield",
					"heading"     	=> esc_html__( "ارتفاع در تبلت", 'studiare' ),
					"param_name"  	=> "sep_height_tablet",
					'options' 		=> array( 'unit' => 'px', 'step' => 1, 'min' => 10, 'max' => 500 ),
					'edit_field_class' => 'vc_col-xs-99'
				),
				array(
					"type"        	=> "textfield",
					"heading"     	=> esc_html__( "ارتفاع در موبایل", 'studiare' ),
					"param_name"  	=> "sep_height_mobile",
					'options' 		=> array( 'unit' => 'px', 'step' => 1, 'min' => 10, 'max' => 500 ),
					'edit_field_class' => 'vc_col-xs-99'
				),
				array(
					"type"        	=> "colorpicker",
					"heading"     	=> esc_html__("رنگ ناحیه اول", 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					"param_name"  	=> "color1",
					"value"  		=> "#a7a7a7",
				),
				array(
					"type"        	=> "colorpicker",
					"heading"     	=> esc_html__("رنگ ناحیه دوم", 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					"param_name"  	=> "color2",
					"value"  		=> "rgba(167,167,167,0.25)",
				),
				array(
					"type"        	=> "colorpicker",
					"heading"     	=> esc_html__("رنگ ناحیه سوم", 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					"param_name"  	=> "color3",
					"value"  		=> "rgba(167,167,167,0.25)",
				),
				array(
					"type"        	=> "checkbox",
					"heading"     	=> esc_html__( "در فضای خالی ساخته شود؟", 'studiare' ),
					"param_name"  	=> "relative",
					'edit_field_class' => 'vc_col-xs-99',
				),
				array(
					"type"        	=> "checkbox",
					"heading"     	=> esc_html__( "اولویت بالا باشد؟", 'studiare' ),
					"param_name"  	=> "priority",
					'edit_field_class' => 'vc_col-xs-99',
				),
				array(
					'type' 			=> 'textfield',
					'param_name' 	=> 'sk_sep',
					"heading"     	=> esc_html__( "کانتینر", 'studiare'),
					'button' 		=> esc_html__( "کانتینر", 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					'settings' 		=> array( 'padding', 'width', 'margin' )
				),
				array( 'type' => 'textfield','param_name' => 'sk_sep_tablet' ),
				array( 'type' => 'textfield','param_name' => 'sk_sep_mobile' ),
				array(
					"type"        	=> "textfield",
					"heading"     	=> esc_html__("کلاس CSS اضافه", 'studiare'),
					'edit_field_class' => 'vc_col-xs-99',
					"param_name"  	=> "class"
				),
			)

		));
if ( class_exists( 'WPBakeryShortCode' ) ) {
	class WPBakeryShortCode_Sc_Separator extends WPBakeryShortCode {}
}		